/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'voucher' : IDL.Null,
  'cash' : IDL.Null,
  'credit' : IDL.Null,
});
export const Pickup = IDL.Record({
  'id' : IDL.Nat,
  'tip' : IDL.Float64,
  'customerName' : IDL.Text,
  'calculatedTotal' : IDL.Float64,
  'city' : IDL.Text,
  'destinationAddress' : IDL.Text,
  'pickupDate' : IDL.Int,
  'meterPaymentMethod' : PaymentMethod,
  'pickupTime' : IDL.Int,
  'meterTotal' : IDL.Float64,
  'phoneNumber' : IDL.Text,
  'tipPaymentMethod' : PaymentMethod,
  'streetAddress' : IDL.Text,
});
export const Customer = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'pickupHistory' : IDL.Vec(Pickup),
  'phoneNumber' : IDL.Text,
  'streetAddress' : IDL.Text,
});
export const ImportExportData = IDL.Record({
  'nextPickupId' : IDL.Opt(IDL.Nat),
  'pickups' : IDL.Vec(Pickup),
  'customers' : IDL.Vec(Customer),
});
export const UserProfile = IDL.Record({
  'contactInfo' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'driverName' : IDL.Text,
});
export const DailyTotals = IDL.Record({
  'creditTotal' : IDL.Float64,
  'calculatedTotal' : IDL.Float64,
  'cashTotal' : IDL.Float64,
  'date' : IDL.Int,
  'periodTotal' : IDL.Float64,
  'creditTipTotal' : IDL.Float64,
  'owedDriver' : IDL.Float64,
  'tipTotal' : IDL.Float64,
  'voucherTotal' : IDL.Float64,
  'cashTipTotal' : IDL.Float64,
  'meterTotal' : IDL.Float64,
  'voucherTipTotal' : IDL.Float64,
});
export const ReportSummary = IDL.Record({
  'totalMeter' : IDL.Float64,
  'totalOwedDriver' : IDL.Float64,
  'totalCashTips' : IDL.Float64,
  'totalCredit' : IDL.Float64,
  'periodTotal' : IDL.Float64,
  'totalCash' : IDL.Float64,
  'totalTips' : IDL.Float64,
  'totalCalculated' : IDL.Float64,
  'totalVoucherTips' : IDL.Float64,
  'totalVoucher' : IDL.Float64,
  'totalCreditTips' : IDL.Float64,
});
export const DailyReport = IDL.Record({
  'dailyTotals' : IDL.Vec(DailyTotals),
  'summary' : ReportSummary,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAllRecords' : IDL.Func([], [], []),
  'deletePickup' : IDL.Func([IDL.Nat], [], []),
  'exportData' : IDL.Func([], [ImportExportData], ['query']),
  'findCustomerByAddress' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(Customer)],
      ['query'],
    ),
  'findCustomerByPhoneNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Customer)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerSuggestions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Customer)],
      ['query'],
    ),
  'getCycleBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getDailyReport' : IDL.Func([IDL.Int, IDL.Int], [DailyReport], ['query']),
  'getPickupById' : IDL.Func([IDL.Nat], [IDL.Opt(Pickup)], ['query']),
  'getPickupsForDate' : IDL.Func([IDL.Int], [IDL.Vec(Pickup)], ['query']),
  'getPickupsInRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Pickup)],
      ['query'],
    ),
  'getStatus' : IDL.Func(
      [],
      [IDL.Record({ 'status' : IDL.Text, 'timestamp' : IDL.Int })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasProfile' : IDL.Func([], [IDL.Bool], ['query']),
  'importData' : IDL.Func([ImportExportData], [], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordPickup' : IDL.Func(
      [
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Float64,
        PaymentMethod,
        IDL.Float64,
        PaymentMethod,
      ],
      [IDL.Nat],
      [],
    ),
  'requireProfile' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePickup' : IDL.Func(
      [
        IDL.Nat,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Float64,
        PaymentMethod,
        IDL.Float64,
        PaymentMethod,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'voucher' : IDL.Null,
    'cash' : IDL.Null,
    'credit' : IDL.Null,
  });
  const Pickup = IDL.Record({
    'id' : IDL.Nat,
    'tip' : IDL.Float64,
    'customerName' : IDL.Text,
    'calculatedTotal' : IDL.Float64,
    'city' : IDL.Text,
    'destinationAddress' : IDL.Text,
    'pickupDate' : IDL.Int,
    'meterPaymentMethod' : PaymentMethod,
    'pickupTime' : IDL.Int,
    'meterTotal' : IDL.Float64,
    'phoneNumber' : IDL.Text,
    'tipPaymentMethod' : PaymentMethod,
    'streetAddress' : IDL.Text,
  });
  const Customer = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'pickupHistory' : IDL.Vec(Pickup),
    'phoneNumber' : IDL.Text,
    'streetAddress' : IDL.Text,
  });
  const ImportExportData = IDL.Record({
    'nextPickupId' : IDL.Opt(IDL.Nat),
    'pickups' : IDL.Vec(Pickup),
    'customers' : IDL.Vec(Customer),
  });
  const UserProfile = IDL.Record({
    'contactInfo' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'driverName' : IDL.Text,
  });
  const DailyTotals = IDL.Record({
    'creditTotal' : IDL.Float64,
    'calculatedTotal' : IDL.Float64,
    'cashTotal' : IDL.Float64,
    'date' : IDL.Int,
    'periodTotal' : IDL.Float64,
    'creditTipTotal' : IDL.Float64,
    'owedDriver' : IDL.Float64,
    'tipTotal' : IDL.Float64,
    'voucherTotal' : IDL.Float64,
    'cashTipTotal' : IDL.Float64,
    'meterTotal' : IDL.Float64,
    'voucherTipTotal' : IDL.Float64,
  });
  const ReportSummary = IDL.Record({
    'totalMeter' : IDL.Float64,
    'totalOwedDriver' : IDL.Float64,
    'totalCashTips' : IDL.Float64,
    'totalCredit' : IDL.Float64,
    'periodTotal' : IDL.Float64,
    'totalCash' : IDL.Float64,
    'totalTips' : IDL.Float64,
    'totalCalculated' : IDL.Float64,
    'totalVoucherTips' : IDL.Float64,
    'totalVoucher' : IDL.Float64,
    'totalCreditTips' : IDL.Float64,
  });
  const DailyReport = IDL.Record({
    'dailyTotals' : IDL.Vec(DailyTotals),
    'summary' : ReportSummary,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAllRecords' : IDL.Func([], [], []),
    'deletePickup' : IDL.Func([IDL.Nat], [], []),
    'exportData' : IDL.Func([], [ImportExportData], ['query']),
    'findCustomerByAddress' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(Customer)],
        ['query'],
      ),
    'findCustomerByPhoneNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Customer)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerSuggestions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Customer)],
        ['query'],
      ),
    'getCycleBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getDailyReport' : IDL.Func([IDL.Int, IDL.Int], [DailyReport], ['query']),
    'getPickupById' : IDL.Func([IDL.Nat], [IDL.Opt(Pickup)], ['query']),
    'getPickupsForDate' : IDL.Func([IDL.Int], [IDL.Vec(Pickup)], ['query']),
    'getPickupsInRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Pickup)],
        ['query'],
      ),
    'getStatus' : IDL.Func(
        [],
        [IDL.Record({ 'status' : IDL.Text, 'timestamp' : IDL.Int })],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasProfile' : IDL.Func([], [IDL.Bool], ['query']),
    'importData' : IDL.Func([ImportExportData], [], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordPickup' : IDL.Func(
        [
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Float64,
          PaymentMethod,
          IDL.Float64,
          PaymentMethod,
        ],
        [IDL.Nat],
        [],
      ),
    'requireProfile' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePickup' : IDL.Func(
        [
          IDL.Nat,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Float64,
          PaymentMethod,
          IDL.Float64,
          PaymentMethod,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };