/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'city' : string,
  'name' : string,
  'pickupHistory' : Array<Pickup>,
  'phoneNumber' : string,
  'streetAddress' : string,
}
export interface DailyReport {
  'dailyTotals' : Array<DailyTotals>,
  'summary' : ReportSummary,
}
export interface DailyTotals {
  'creditTotal' : number,
  'calculatedTotal' : number,
  'cashTotal' : number,
  'date' : bigint,
  'creditTipTotal' : number,
  'owedDriver' : number,
  'tipTotal' : number,
  'voucherTotal' : number,
  'cashTipTotal' : number,
  'meterTotal' : number,
  'voucherTipTotal' : number,
}
export interface ExportData {
  'pickups' : Array<Pickup>,
  'customers' : Array<Customer>,
}
export type PaymentMethod = { 'voucher' : null } |
  { 'cash' : null } |
  { 'credit' : null };
export interface Pickup {
  'id' : bigint,
  'tip' : number,
  'customerName' : string,
  'calculatedTotal' : number,
  'city' : string,
  'destinationAddress' : string,
  'pickupDate' : bigint,
  'meterPaymentMethod' : PaymentMethod,
  'pickupTime' : bigint,
  'meterTotal' : number,
  'phoneNumber' : string,
  'tipPaymentMethod' : PaymentMethod,
  'streetAddress' : string,
}
export interface ReportSummary {
  'totalMeter' : number,
  'totalOwedDriver' : number,
  'totalCashTips' : number,
  'totalCredit' : number,
  'totalCash' : number,
  'totalTips' : number,
  'totalCalculated' : number,
  'totalVoucherTips' : number,
  'totalVoucher' : number,
  'totalCreditTips' : number,
}
export interface UserProfile {
  'contactInfo' : string,
  'email' : [] | [string],
  'driverName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAllRecords' : ActorMethod<[], undefined>,
  'deletePickup' : ActorMethod<[bigint], undefined>,
  'exportData' : ActorMethod<[], ExportData>,
  'findCustomerByAddress' : ActorMethod<[string, string], [] | [Customer]>,
  'findCustomerByPhoneNumber' : ActorMethod<[string], [] | [Customer]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerSuggestions' : ActorMethod<[string], Array<Customer>>,
  'getCycleBalance' : ActorMethod<[], bigint>,
  'getDailyReport' : ActorMethod<[bigint, bigint], DailyReport>,
  'getPickupById' : ActorMethod<[bigint], [] | [Pickup]>,
  'getPickupsForDate' : ActorMethod<[bigint], Array<Pickup>>,
  'getPickupsInRange' : ActorMethod<[bigint, bigint], Array<Pickup>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasProfile' : ActorMethod<[], boolean>,
  'importData' : ActorMethod<[ExportData], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordPickup' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      bigint,
      string,
      number,
      PaymentMethod,
      number,
      PaymentMethod,
    ],
    bigint
  >,
  'requireProfile' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePickup' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      bigint,
      string,
      number,
      PaymentMethod,
      number,
      PaymentMethod,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];