/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Pickup {
    id: bigint;
    tip: number;
    customerName: string;
    calculatedTotal: number;
    city: string;
    destinationAddress: string;
    pickupDate: bigint;
    meterPaymentMethod: PaymentMethod;
    pickupTime: bigint;
    meterTotal: number;
    phoneNumber: string;
    tipPaymentMethod: PaymentMethod;
    streetAddress: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ImportExportData {
    nextPickupId?: bigint;
    pickups: Array<Pickup>;
    customers: Array<Customer>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface DailyTotals {
    creditTotal: number;
    calculatedTotal: number;
    cashTotal: number;
    date: bigint;
    periodTotal: number;
    creditTipTotal: number;
    owedDriver: number;
    tipTotal: number;
    voucherTotal: number;
    cashTipTotal: number;
    meterTotal: number;
    voucherTipTotal: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DailyReport {
    dailyTotals: Array<DailyTotals>;
    summary: ReportSummary;
}
export interface Customer {
    city: string;
    name: string;
    pickupHistory: Array<Pickup>;
    phoneNumber: string;
    streetAddress: string;
}
export interface UserProfile {
    contactInfo: string;
    email?: string;
    driverName: string;
}
export interface ReportSummary {
    totalMeter: number;
    totalOwedDriver: number;
    totalCashTips: number;
    totalCredit: number;
    periodTotal: number;
    totalCash: number;
    totalTips: number;
    totalCalculated: number;
    totalVoucherTips: number;
    totalVoucher: number;
    totalCreditTips: number;
}
export enum PaymentMethod {
    voucher = "voucher",
    cash = "cash",
    credit = "credit"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAllRecords(): Promise<void>;
    deletePickup(pickupId: bigint): Promise<void>;
    exportData(): Promise<ImportExportData>;
    findCustomerByAddress(streetAddress: string, city: string): Promise<Customer | null>;
    findCustomerByPhoneNumber(phoneNumber: string): Promise<Customer | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomerSuggestions(partialInput: string): Promise<Array<Customer>>;
    getCycleBalance(): Promise<bigint>;
    getDailyReport(fromDate: bigint, toDate: bigint): Promise<DailyReport>;
    getPickupById(pickupId: bigint): Promise<Pickup | null>;
    getPickupsForDate(selectedDate: bigint): Promise<Array<Pickup>>;
    getPickupsInRange(fromDate: bigint, toDate: bigint): Promise<Array<Pickup>>;
    getStatus(): Promise<{
        status: string;
        timestamp: bigint;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasProfile(): Promise<boolean>;
    importData(data: ImportExportData): Promise<void>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    recordPickup(pickupDate: bigint, streetAddress: string, city: string, customerName: string, phoneNumber: string, pickupTime: bigint, destinationAddress: string, meterTotal: number, meterPaymentMethod: PaymentMethod, tip: number, tipPaymentMethod: PaymentMethod): Promise<bigint>;
    requireProfile(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updatePickup(pickupId: bigint, pickupDate: bigint, streetAddress: string, city: string, customerName: string, phoneNumber: string, pickupTime: bigint, destinationAddress: string, meterTotal: number, meterPaymentMethod: PaymentMethod, tip: number, tipPaymentMethod: PaymentMethod): Promise<void>;
}
import type { Customer as _Customer, ImportExportData as _ImportExportData, PaymentMethod as _PaymentMethod, Pickup as _Pickup, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAllRecords(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllRecords();
            return result;
        }
    }
    async deletePickup(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePickup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePickup(arg0);
            return result;
        }
    }
    async exportData(): Promise<ImportExportData> {
        if (this.processError) {
            try {
                const result = await this.actor.exportData();
                return from_candid_ImportExportData_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportData();
            return from_candid_ImportExportData_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async findCustomerByAddress(arg0: string, arg1: string): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.findCustomerByAddress(arg0, arg1);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findCustomerByAddress(arg0, arg1);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async findCustomerByPhoneNumber(arg0: string): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.findCustomerByPhoneNumber(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findCustomerByPhoneNumber(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerSuggestions(arg0: string): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerSuggestions(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerSuggestions(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCycleBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCycleBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCycleBalance();
            return result;
        }
    }
    async getDailyReport(arg0: bigint, arg1: bigint): Promise<DailyReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyReport(arg0, arg1);
            return result;
        }
    }
    async getPickupById(arg0: bigint): Promise<Pickup | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPickupById(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPickupById(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPickupsForDate(arg0: bigint): Promise<Array<Pickup>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPickupsForDate(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPickupsForDate(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPickupsInRange(arg0: bigint, arg1: bigint): Promise<Array<Pickup>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPickupsInRange(arg0, arg1);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPickupsInRange(arg0, arg1);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStatus(): Promise<{
        status: string;
        timestamp: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatus();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasProfile(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasProfile();
            return result;
        }
    }
    async importData(arg0: ImportExportData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importData(to_candid_ImportExportData_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importData(to_candid_ImportExportData_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordPickup(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: string, arg7: number, arg8: PaymentMethod, arg9: number, arg10: PaymentMethod): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPickup(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_PaymentMethod_n33(this._uploadFile, this._downloadFile, arg8), arg9, to_candid_PaymentMethod_n33(this._uploadFile, this._downloadFile, arg10));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPickup(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_PaymentMethod_n33(this._uploadFile, this._downloadFile, arg8), arg9, to_candid_PaymentMethod_n33(this._uploadFile, this._downloadFile, arg10));
            return result;
        }
    }
    async requireProfile(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requireProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requireProfile();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePickup(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint, arg7: string, arg8: number, arg9: PaymentMethod, arg10: number, arg11: PaymentMethod): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePickup(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_PaymentMethod_n33(this._uploadFile, this._downloadFile, arg9), arg10, to_candid_PaymentMethod_n33(this._uploadFile, this._downloadFile, arg11));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePickup(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_PaymentMethod_n33(this._uploadFile, this._downloadFile, arg9), arg10, to_candid_PaymentMethod_n33(this._uploadFile, this._downloadFile, arg11));
            return result;
        }
    }
}
function from_candid_Customer_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ImportExportData_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImportExportData): ImportExportData {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Pickup_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Pickup): Pickup {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : from_candid_Customer_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Pickup]): Pickup | null {
    return value.length === 0 ? null : from_candid_Pickup_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nextPickupId: [] | [bigint];
    pickups: Array<_Pickup>;
    customers: Array<_Customer>;
}): {
    nextPickupId?: bigint;
    pickups: Array<Pickup>;
    customers: Array<Customer>;
} {
    return {
        nextPickupId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.nextPickupId)),
        pickups: from_candid_vec_n12(_uploadFile, _downloadFile, value.pickups),
        customers: from_candid_vec_n17(_uploadFile, _downloadFile, value.customers)
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    tip: number;
    customerName: string;
    calculatedTotal: number;
    city: string;
    destinationAddress: string;
    pickupDate: bigint;
    meterPaymentMethod: _PaymentMethod;
    pickupTime: bigint;
    meterTotal: number;
    phoneNumber: string;
    tipPaymentMethod: _PaymentMethod;
    streetAddress: string;
}): {
    id: bigint;
    tip: number;
    customerName: string;
    calculatedTotal: number;
    city: string;
    destinationAddress: string;
    pickupDate: bigint;
    meterPaymentMethod: PaymentMethod;
    pickupTime: bigint;
    meterTotal: number;
    phoneNumber: string;
    tipPaymentMethod: PaymentMethod;
    streetAddress: string;
} {
    return {
        id: value.id,
        tip: value.tip,
        customerName: value.customerName,
        calculatedTotal: value.calculatedTotal,
        city: value.city,
        destinationAddress: value.destinationAddress,
        pickupDate: value.pickupDate,
        meterPaymentMethod: from_candid_PaymentMethod_n15(_uploadFile, _downloadFile, value.meterPaymentMethod),
        pickupTime: value.pickupTime,
        meterTotal: value.meterTotal,
        phoneNumber: value.phoneNumber,
        tipPaymentMethod: from_candid_PaymentMethod_n15(_uploadFile, _downloadFile, value.tipPaymentMethod),
        streetAddress: value.streetAddress
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city: string;
    name: string;
    pickupHistory: Array<_Pickup>;
    phoneNumber: string;
    streetAddress: string;
}): {
    city: string;
    name: string;
    pickupHistory: Array<Pickup>;
    phoneNumber: string;
    streetAddress: string;
} {
    return {
        city: value.city,
        name: value.name,
        pickupHistory: from_candid_vec_n12(_uploadFile, _downloadFile, value.pickupHistory),
        phoneNumber: value.phoneNumber,
        streetAddress: value.streetAddress
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactInfo: string;
    email: [] | [string];
    driverName: string;
}): {
    contactInfo: string;
    email?: string;
    driverName: string;
} {
    return {
        contactInfo: value.contactInfo,
        email: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.email)),
        driverName: value.driverName
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    voucher: null;
} | {
    cash: null;
} | {
    credit: null;
}): PaymentMethod {
    return "voucher" in value ? PaymentMethod.voucher : "cash" in value ? PaymentMethod.cash : "credit" in value ? PaymentMethod.credit : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Pickup>): Array<Pickup> {
    return value.map((x)=>from_candid_Pickup_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Customer>): Array<Customer> {
    return value.map((x)=>from_candid_Customer_n18(_uploadFile, _downloadFile, x));
}
function to_candid_Customer_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Customer): _Customer {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_ImportExportData_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImportExportData): _ImportExportData {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_Pickup_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Pickup): _Pickup {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nextPickupId?: bigint;
    pickups: Array<Pickup>;
    customers: Array<Customer>;
}): {
    nextPickupId: [] | [bigint];
    pickups: Array<_Pickup>;
    customers: Array<_Customer>;
} {
    return {
        nextPickupId: value.nextPickupId ? candid_some(value.nextPickupId) : candid_none(),
        pickups: to_candid_vec_n30(_uploadFile, _downloadFile, value.pickups),
        customers: to_candid_vec_n35(_uploadFile, _downloadFile, value.customers)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    tip: number;
    customerName: string;
    calculatedTotal: number;
    city: string;
    destinationAddress: string;
    pickupDate: bigint;
    meterPaymentMethod: PaymentMethod;
    pickupTime: bigint;
    meterTotal: number;
    phoneNumber: string;
    tipPaymentMethod: PaymentMethod;
    streetAddress: string;
}): {
    id: bigint;
    tip: number;
    customerName: string;
    calculatedTotal: number;
    city: string;
    destinationAddress: string;
    pickupDate: bigint;
    meterPaymentMethod: _PaymentMethod;
    pickupTime: bigint;
    meterTotal: number;
    phoneNumber: string;
    tipPaymentMethod: _PaymentMethod;
    streetAddress: string;
} {
    return {
        id: value.id,
        tip: value.tip,
        customerName: value.customerName,
        calculatedTotal: value.calculatedTotal,
        city: value.city,
        destinationAddress: value.destinationAddress,
        pickupDate: value.pickupDate,
        meterPaymentMethod: to_candid_PaymentMethod_n33(_uploadFile, _downloadFile, value.meterPaymentMethod),
        pickupTime: value.pickupTime,
        meterTotal: value.meterTotal,
        phoneNumber: value.phoneNumber,
        tipPaymentMethod: to_candid_PaymentMethod_n33(_uploadFile, _downloadFile, value.tipPaymentMethod),
        streetAddress: value.streetAddress
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city: string;
    name: string;
    pickupHistory: Array<Pickup>;
    phoneNumber: string;
    streetAddress: string;
}): {
    city: string;
    name: string;
    pickupHistory: Array<_Pickup>;
    phoneNumber: string;
    streetAddress: string;
} {
    return {
        city: value.city,
        name: value.name,
        pickupHistory: to_candid_vec_n30(_uploadFile, _downloadFile, value.pickupHistory),
        phoneNumber: value.phoneNumber,
        streetAddress: value.streetAddress
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactInfo: string;
    email?: string;
    driverName: string;
}): {
    contactInfo: string;
    email: [] | [string];
    driverName: string;
} {
    return {
        contactInfo: value.contactInfo,
        email: value.email ? candid_some(value.email) : candid_none(),
        driverName: value.driverName
    };
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    voucher: null;
} | {
    cash: null;
} | {
    credit: null;
} {
    return value == PaymentMethod.voucher ? {
        voucher: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value == PaymentMethod.credit ? {
        credit: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Pickup>): Array<_Pickup> {
    return value.map((x)=>to_candid_Pickup_n31(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Customer>): Array<_Customer> {
    return value.map((x)=>to_candid_Customer_n36(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
